-- 코드를 작성해주세요
SELECT 
    CONCAT(
        CASE
            WHEN 0 < MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) < 4 THEN 1
            WHEN 3 < MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) < 7 THEN 2
            WHEN 6 < MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) < 10 THEN 3
            WHEN 9 < MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) < 13 THEN 4
        END, "Q") AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER