SELECT YEAR(ED_ORIGIN.DIFFERENTIATION_DATE) AS YEAR,
       (
           SELECT MAX(ED_MAX.SIZE_OF_COLONY)
           FROM ECOLI_DATA ED_MAX
           WHERE YEAR(ED_MAX.DIFFERENTIATION_DATE) = YEAR(ED_ORIGIN.DIFFERENTIATION_DATE)
       ) - ED_ORIGIN.SIZE_OF_COLONY AS YEAR_DEV,
       ED_ORIGIN.ID
FROM ECOLI_DATA ED_ORIGIN
ORDER BY YEAR, YEAR_DEV