-- 코드를 입력하세요
SELECT DISTINCT(CRCRH.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE MONTH(CRCRH.START_DATE) = 10 AND CRCC.CAR_TYPE = '세단'
ORDER BY CRCRH.CAR_ID DESC